export const menuItems = {
  appetizers: [
    {
      title: 'Egg Roll',
      description:
        'A cylindrical, savory roll with shredded cabbage, chopped pork, and other fillings inside a thickly-wrapped wheat flour skin, which is fried in hot oil.',
      price: '1.39',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Egg Rolls 5pc.',
      description:
        'A cylindrical, savory roll with shredded cabbage, chopped pork, and other fillings inside a thickly-wrapped wheat flour skin, which is fried in hot oil.',
      price: '6.50',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Spring Roll',
      description:
        'A cylindrical roll of rice paper, or sometimes wheat-and-egg dough, filled with a shredded mixture of vegetables and often meat or seafood, served fresh or deep-fried.',
      price: '1.59',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Spring Rolls 5pc.',
      description:
        'A cylindrical roll of rice paper, or sometimes wheat-and-egg dough, filled with a shredded mixture of vegetables and often meat or seafood, served fresh or deep-fried.',
      price: '7.50',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Beef on Sticks 4pc.',
      description: '',
      price: '6.99',
      spice: 0,
      tag: ['appetizer', 'side', 'beef'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Chicken on Sticks 4pc.',
      description: '',
      price: '6.99',
      spice: 0,
      tag: ['appetizer', 'side', 'chicken'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Shrimp Toast 6pcs.',
      description: '',
      price: '4.99',
      spice: 0,
      tag: ['appetizer', 'side', 'shrimp', 'seafood'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Fried Chicken Wings 4pcs.',
      description: '',
      price: '4.55',
      spice: 0,
      tag: ['appetizer', 'side', 'chicken'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Fried Chicken Wings 8pcs.',
      description: '',
      price: '7.99',
      spice: 0,
      tag: ['appetizer', 'side', 'chicken'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Spicy Chicken Wings 8pcs.',
      description: '',
      price: '8.50',
      spice: 3,
      tag: ['appetizer', 'side', 'chicken', 'spicy'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Buffalo Chicken Wings 8pcs.',
      description: '',
      price: '8.50',
      spice: 3,
      tag: ['appetizer', 'side', 'chicken', 'spicy'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Fried Cream Cheese Wonton 8pcs.',
      description: '',
      price: '4.99',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Boneless Spare Ribs 6pcs.',
      description: '',
      price: '6.55',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Boneless Spare Ribs 6pcs.',
      description: '',
      price: '6.55',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Steamed Dumplings 6pcs.',
      description: '',
      price: '5.25',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Fried Dumplings 6pcs.',
      description: '',
      price: '5.25',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Chinese Donuts 10pcs.',
      description: '',
      price: '3.99',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'French Fries',
      description: '',
      price: '2.25',
      spice: 0,
      tag: ['appetizer', 'side'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
    {
      title: 'Fried Scallops 10pcs.',
      description: '',
      price: '5.25',
      spice: 0,
      tag: ['appetizer', 'side', 'seafood'],
      img_src: '/assets/images/garlic-chicken.jpeg',
    },
  ],

  rice: [
    {
      title: 'Chicken Fried Rice Small',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'chicken'],
    },

    {
      title: 'Roast Pork Fried Rice',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'pork'],
    },

    {
      title: 'Beef Fried Rice',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'beef'],
    },

    {
      title: 'Shrimp Fried Rice',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'seafood', 'shrimp'],
    },

    {
      title: 'Ham Fried Rice',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'pork'],
    },

    {
      title: 'Vegetable Fried Rice',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'vegetable'],
    },

    {
      title: 'House Fried Rice',
      description: '',
      price: { small: '6.99', large: '8.55' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'shrimp', 'pork', 'chicken'],
    },

    {
      title: 'Seafood Fried Rice',
      description: '',
      price: { small: '6.05', large: '7.65' },
      spice: 0,
      tag: ['rice', 'fried rice', 'side', 'shrimp', 'seafood'],
    },
  ],

  lo_mein: [
    {
      title: 'Plain Lo Mein',
      description: '',
      price: {
        small: '5.50',
        large: '7.50',
      },
      spice: 0,
      tag: ['lo mein'],
    },
    {
      title: 'Chicken Lo Mein',
      description: '',
      price: {
        small: '6.65',
        large: '8.10',
      },
      spice: 0,
      tag: ['lo mein', 'chicken'],
    },
    {
      title: 'Roast Pork Lo Mein',
      description: '',
      price: {
        small: '6.65',
        large: '8.10',
      },
      spice: 0,
      tag: ['lo mein', 'pork'],
    },
    {
      title: 'Beef Lo Mein',
      description: '',
      price: {
        small: '6.65',
        large: '8.10',
      },
      spice: 0,
      tag: ['lo mein', 'beef'],
    },
    {
      title: 'Shrimp Lo Mein',
      description: '',
      price: {
        small: '6.65',
        large: '8.10',
      },
      spice: 0,
      tag: ['lo mein', 'shrimp', 'seafood'],
    },
    {
      title: 'Vegetable Lo Mein',
      description: '',
      price: {
        small: '6.65',
        large: '8.10',
      },
      spice: 0,
      tag: ['lo mein', 'vegetable'],
    },
    {
      title: 'House Special Lo Mein',
      description: '',
      price: {
        small: '7.55',
        large: '8.99',
      },
      spice: 0,
      tag: ['lo mein', 'shrimp', 'pork', 'chicken'],
    },
    {
      title: 'Seafood Lo Mein',
      description: '',
      price: {
        small: '7.55',
        large: '8.99',
      },
      spice: 0,
      tag: ['lo mein', 'seafood', 'shrimp'],
    },
  ],

  mei_fun: [
    {
      title: 'House Special Chow Mei Fun',
      description: '',
      price: '8.99',
      spice: 0,
      tag: ['mai fun'],
    },
    {
      title: 'Singapore Chow Mei Fun',
      description: '',
      price: '8.99',
      spice: 3,
      tag: ['mai fun'],
    },
    {
      title: 'House Special Chow Mei Fun',
      description: '',
      price: '8.99',
      spice: 0,
      tag: ['mai fun'],
    },
  ],
  dinner_platters: {
    chicken: [
      {
        title: 'Garlic Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Chicken Chow Mein',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Chicken with Broccoli',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Moo Goo Gai Pan',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Chicken with Cashew Nuts',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Boneless Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Lemon Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Honey Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Woo Shu Gai',
        description: '',
        price: { small: '6.65', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Garlic Honey Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Chicken with Chinese Vegetables',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Sweet and Sour Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Seasame Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Orange Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Almond Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Pineapple Chicken',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Chicken with Mushroom',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Bourbon Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Black Bean Sauce Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Kung Po Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Sha Cha Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Mongolian Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Curry Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Mandarin Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Szechuan Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Yu Shian Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'General Chicken',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['chicken'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
    ],
    pork: [
      {
        title: 'Sweet and Sour Pork',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['pork'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Pork with Chinese Vegetables',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['pork'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Garlic Pork',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['pork'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Yu Shian Pork',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['pork'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Hunan Pork',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['pork'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
    ],
    beef: [
      {
        title: 'Beef Chow Mein',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Beef with Broccoli',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Green Pepper Steak',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Beef Chop Suey',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Beef with Cashew Nuts',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Beef with Chinese Vegetables',
        description: '',
        price: { small: '6.65', large: '8.10' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Beef with Bean Sprout',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 0,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Kung Po Beef',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Mongolian Beef',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Curry Beef',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Yo Shian Beef',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Hunan Beef',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
      {
        title: 'Sha Cha Beef',
        description: '',
        price: { small: '6.99', large: '8.99' },
        spice: 3,
        tag: ['beef'],
        img_src: '/assets/images/garlic-chicken.jpeg',
      },
    ],
    seafood: [],
  },
  lunch: [],
  dinner_combos: [],
  diet: [],
  special_platters: [],
  childrens: [],
};
